### ISSUE TITLE
Getting Tests Up And Running

### ISSUE THREAD

**Issue by philanderson888** [nishman89/2019-12_CSharpWalkthrough#1]
General notes and comments on getting tests up and working

**Comment by philanderson888** [comment]
/* TestCase Attribute - 
		 * I remember when I did a practice test case, 
		 * using xunit and following a tutorial on Pluralsight, 
		 * the lay out was totally different. 
		   Also, the structure is different to the test cases on the 
		   NewCSharpCurriculum on github	
		   */

**Comment by philanderson888** [comment]
You are correct.

Most of the tests I wrote initially when I wrote the curriculum are using the default MSTest which is built into Microsoft.

However NUnit is an industry standard and so I use that one.

XUnit is newer still and I could also use that one, but NUnit is the default one which I think is a good middle ground for now.

If I were you I would be aware of all three and learn how to use all three, which I quite often teach my students, but we choose one for working out our every day tests and I have gone for NUnit.

**Comment by philanderson888** [comment]
![image](https://user-images.githubusercontent.com/8657188/70985908-d6e8bb00-20b4-11ea-9702-e50b07ad73c7.png)

**Comment by philanderson888** [comment]
Hey Nish - look at this!  Your test is failing because the value is 6.2000000000002 so it's not precisely the value you are looking for.  Refactor the test to be greater than 6.199 and less than 6.209 for example!  Or whatever precision you are looking for.  Let me know how you get on.

I've also fixed any other errors and replied to one or two of your questions! 

Phil 

:)

**Comment by philanderson888** [comment]
Do a git pull and try again!  Let me know when done

**Comment by nishman89** [comment]
Done
