### ISSUE TITLE
yield return

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#2]
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System.Text;

namespace Lab_04_Conditional_Operators //cant con
{
	class Program
	{
	public	static void Main(string[] args)
		{
			ConditionalOperators.Loops();
		}
	}
	public class ConditionalOperators
	{
	    public static IEnumerable<int> Loops()
		{
			for (int i = 1; i <= 25; i++)
			{
				if (i % 3 == 0)
				{
					yield return i;
				}
			}
			
		}
	}

**Comment by nishman89** [comment]
when I run the above code, it works fine. However, if I want to see the results of the return and write Console.WriteLine(ConditionalOperators.Loops()) I do not get a print of all the values in the terminal. However, if the iterative method was in the main method e.g. Console.WriteLine(i), I get what I want. Does that make sense? Is there a way to output the yield return results in the terminal?

**Comment by philanderson888** [comment]
I think when you Console.WriteLine(i) then it prints out an integer OK

**Comment by philanderson888** [comment]
I think that's closed !

**Comment by nishman89** [comment]
That's amazing. Thanks Phil!
