### ISSUE TITLE
What I plan to cover

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#3]
**w/c 16/12/2019 :**
Complete Labs: 

12 - Classes
13 - Methods
16 - Polymorphism
19 - Collections
21 -Unit Testing

**w/c 23/12/2019:**
TBC (will update Friday 20th Dec)

**Comment by philanderson888** [comment]
Cool

**Comment by philanderson888** [comment]
Cool, just update it at least every 2-3 days.  I find if I do a daily focus plan I will achieve a lot more.

**Comment by philanderson888** [comment]
Switch lab looks fine

**Comment by philanderson888** [comment]
In 

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Lab_05_ValRefTypes/Program.cs

Does this make sense?

//we will find that the changes affect both the arrays exactly the same when this is run.
//What we find is that when we copy a reference type we only copy the pointer to the same object; we do not actually create a new object.

**Comment by nishman89** [comment]
I understand it (I cut and pasted it from what was written on the NewCSharpCurriculum as a reminder), but it took me a while to get my head around what it was actually saying.

**Comment by nishman89** [comment]
I am currently doing the modifiers lab. So I am behind where I would like to get to. I plan to, before 2nd January to know enough to create a game on Unity. I will keep you updated if I start before then, and send screen shots. The new Brum trainer will be starting 2nd January.

**Comment by philanderson888** [comment]
I see - thanks for the update.  Just keep 'blogging' here as you work - successes, failures, each time you commit etc.

**Comment by philanderson888** [comment]
I can provide encouragement, motivation and probably some great time-saving tips.  If you let me know your plan for the next lab I can give any tips etc.

**Comment by philanderson888** [comment]
Lab 08 Classes - Good stuff :)

**Comment by nishman89** [comment]
Thanks Phil :) sorry for the late reply. Been spending the morning trying to find out the best way to explain the 4 principles of OOP. I've started doing the methods lab, and it's okay. However, I don't think I am doing some of it correctly. I want to return both the sum and the product values, but not sure if this is possible at all, unless I create another class for these methods (such as with the calculator). I will push up what I've done so far, but will update with my finished ab later on today. I plan for tomorrow to have started Lab_16 polymorphisms. Thanks again for everything :) don't worry about getting back to this until after the NYs!! Also, wish you have a great Xmas and NY!

**Comment by philanderson888** [comment]
Use a tuple which just puts a bracket around the two values

(int, int) MyMethod(int a, int b){
  return (a+b,a*b);
}

Simple !

**Comment by philanderson888** [comment]
OOP
Inheritance : parent to child
Encapsulation : private keyword hides members
Abstraction : public keyword on properties can be used to expose private members via {get;set;}  (think car engine : private engine exposed by public gear stick, clutch, throttle and steering wheel)
Polymorphism : many types eg Family Adams : Parents have a party but children 'override' default parent behaviour to hold their own style of party!

Easy!

**Comment by nishman89** [comment]
Amazing, thanks Phil :) will have a  go now. Hope you have a lovely Christmas!

**Comment by philanderson888** [comment]
Hey Nish with your guided learning by yourself I would recommend doing, in order

https://github.com/spartaglobal/NewCSharpCurriculum/tree/master/16-polymorphism

https://github.com/spartaglobal/NewCSharpCurriculum/tree/master/17-interfaces but this is not critical to the rest of the course so maybe just give it a little go for now and move on and come back to it later.  If you have someone a bit more experienced in January / February she can perhaps guide you with learning about interfaces.

https://github.com/spartaglobal/NewCSharpCurriculum/tree/master/19-collections

Let me know how you get on :)

**Comment by nishman89** [comment]
Hey Phil, I've moved straight to collections, the lab for which I will try to complete today. Also, will move on to "21 - Unit Testing" today. Anything I do not complete, I will complete tomorrow. I will push anything I've done (finished or not) at 5 :)

**Comment by philanderson888** [comment]
Your work on collections here

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Lab_12_Part1_Collections/Program.cs

looks complete and of a very high quality - well done Nish!

**Comment by philanderson888** [comment]
### Testing

If you do plan on doing the testing I wouldn't waste much time on it.  I think what I've found is the MSTest framework is a bit old and 'clunky' so I am deferring almost completely to the NUnit.

**Comment by nishman89** [comment]
Great, thanks Phil. Will finish up the the Collections lab tomorrow and will focus on just NUnit testing (though like you said familiarise myself with the other frameworks)! Thanks for your help Phil and I'll speak to you next decade :)

**Comment by philanderson888** [comment]
Likewise!!!

**Comment by nishman89** [comment]
Hi Phil - sorry for keeping you updated. I have completed a WPF tutorial (ExpenseIt and TicTacToe). I will be moving on to the Linq Labs and then planning on doing another WPF game.

**Comment by philanderson888** [comment]
Well done Nish

I've got 2 ideas

After the LINQ labs.....

1) I created an OOP Rabbit lab which I would like you to have a go at.  

class Rabbit {
   public string RabbitId {get;set;}
   public int Age {get;set;
   public string RabbitName {get;set;}
}

Create a world where time=loop=0 there is 1 solitary rabbit.

Each loop every rabbit spawns one rabbit.

Write a test to check how many loops before the rabbit population reaches a given ceiling eg 1 million rabbits.

Then alter it to not permit new rabbits until the age is, say 3 ie cannot spawn until age>=3

See how you get on!

Second thought

It's a bit crazy but I have found WPF just doesn't 'do it' when it comes to interviews and clients.  What I have found is Unity can be quite exciting both for students and clients coming in as there is a tangible visual aspect to the work being produced, and it's very fun.  Think about it - your call - perhaps set yourself a trivial task of creating a very crude and basic Unity game from scratch - kind of 'Hello World' - and see how you get on.  Just a thought!  When you run the class you will find if any students can build in Unity it will create quite a 'buzz' in the class so that's what I'm thinking.  Also if you can't do it or find it too hard, be aware the students who come on the course may be able to help!

Let me know your (and Cathy) thoughts on this

Take care and keep me updated!

Phil

PS I don't do the Unity myself!

**Comment by nishman89** [comment]
Thanks, Phil! Me and Cathy will be going through the SQL, Entity and LINQ labs today, I will play around with Unity and this weekend. Also, will do that Lab once I've finished the LINQ stuff!

**Comment by philanderson888** [comment]
Sounds good

**Comment by philanderson888** [comment]
Maybe if Cathy has a github invite her in so we can both help and contribute to your progress?

**Comment by nishman89** [comment]
I've sent an invite - just pending a accept. She's been reviewing some of my code and anything I've struggled with as we're sitting next to each other when I do the labs :)

**Comment by philanderson888** [comment]
Cool :)
