### ISSUE TITLE
Lab_06

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#4]
Keep getting error "object reference not set to an instance of an object".

**Comment by philanderson888** [comment]
I've fixed your code Nish

1) This works best if you divide by integer zero - see example here (first one)

https://docs.microsoft.com/en-us/dotnet/api/system.dividebyzeroexception?view=netframework-4.8

and further discussion here

https://stackoverflow.com/questions/4262286/why-does-c-sharp-allow-dividing-a-non-zero-number-by-zero-in-floating-point-type

2) No need to create that extra class so I have removed it completely

Phil

:)

**Comment by philanderson888** [comment]
Issue resolved :) Let me know!

**Comment by philanderson888** [comment]
Also I think you can remove this file

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Lab_06_Exceptions/Lab_06_Exceptions.sln

As you only need one solution (container) file.

You already have the main solution file at

https://github.com/nishman89/2019-12_CSharpWalkthrough/blob/master/Labs.sln

Inside Visual Studio just right click on the solution in Solution Explorer and choose Add, New Project.  For all new projects :)

Well done, going good!

**Comment by nishman89** [comment]
Thank you, Phil. 

I created another class to put the 'divide by zero' method in just to try it out that way. Is there a way to do make it work that way? Also, thanks for pointing out the sln file mistake!!

**Comment by philanderson888** [comment]
Did you push your commit?  I cannot see the class.

In general I would not create a class unless there is a clear need.

When we are running tests, yes, it is good to create a class for example.

**Comment by nishman89** [comment]
Cheers!
