### ISSUE TITLE
Lab_13 methods

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#5]
Completed lab 13, though I do not understand what the lab is asking from me in regards to the JSON stuff? I've completed it to the best I could, but is it possible to have a quick convo about it after Xmas, if that's okay. Thank you :)

**Comment by philanderson888** [comment]
Did you push it ? Same to you :)

**Comment by philanderson888** [comment]
Hi Nish

The JSON item at the end was just an alternative to printing out the cat's details at the end.

Normally we would use Console.WriteLine and syntax something like this:

1) Create Cat class with Name and Age properties using public string Name {get;set;} and public int Age {get;set;}.
2) Add the constructor public Cat(string Name, int Age){this.Name=Name; this.Age=Age;}
3) Add method void IncrementAge(Cat cat) {
    cat.Age += 5;
}  
Notice that this method can be outside of the Cat class eg 
public static void Main(){

}
static void IncrementCat(Cat cat){ ... }
4) Instantiate a cat    var cat01 = new Cat("Tibby",2);
5) Call the IncrementAge method ie IncrementAge(cat01);
6) Repeat this ie call the same method again
7) Print out the cat age Console.WriteLine(cat01.Age); and should be 12
8) Just for variation we can also print out the cat details by converting to JSON 
   a) using System.Web.Script.Serialization; (note you must add a Reference first - you will have to 
       Google for the reference name to add)
   b) var json = new JavaScriptSerializer().Serialize(cat01); 
   c) Console.WriteLine(json);  // or .ToString();  
and this will just print out the Cat name and age as a JSON object.  

See if this helps.

Main goal of the lesson is to see that we can not only have methods in a class but also methods which pass in a class instance and manipulate that class instance.
Cat cat01 = new Cat("Tilly,2);
IncrementAge(cat01){ // pass in cat01 and increment the age here }

Hope that helps

Phil

:)


Don't look at the answer until you've had a good shot at doing it yourself

Phil

https://github.com/spartaglobal/NewCSharpCurriculum/blob/master/13-methods/lab-13-methods/solution-code/Lab-13-methods/Methods.cs

https://github.com/spartaglobal/NewCSharpCurriculum/blob/master/13-methods/lab-13-methods/solution-code/Lab-13-methodsTests/MethodsTests.cs

Again, I've done this in a very detailed and particular way but there's no real need for you to have to do it this way - just understanding the concepts is fine :)

**Comment by nishman89** [comment]
Thank you, that helped a bunch!!! I have successfully completed the lab :) I will push up after I have completed the polymorphism lab (won't forget to do it this time) 
:)

**Comment by philanderson888** [comment]
Cool will look forward to seeing it!

**Comment by nishman89** [comment]
Hey Phil - have completed the polymorphic lab - I got the methods correct, however, I did look at the solution for each time I called the Grow method (my one was a bit too convoluted!).  

I had to do a bit of googling but I was having issues with my child classes so had to use the 'base' keyword (i'm not 100% sure what it does, but I juts googled it). If there is any other way to improve it, please let me know :)
