### ISSUE TITLE
What does "an object is required for nonstatic fields" mean exactly...

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#7]
If I'm calling a method from the Main method, and I'm not "pushing" an object through, but just calling the method, I get the above error message? I'm assuming this will always be the case, and static means that not object, variable etc can be pushed through static methods then?

**Comment by philanderson888** [comment]
Do you have the code snippet Nish?

static methods are called via the Class and never the instance

Class MyClass{
     void DoThis(){}
    static void DoThat(){}
}

We talk to both methods in this manner

class Program{
   static void Main(){
       // static
      MyClass.DoThat();

     // instance
    var instance = new MyClass();
    instance.DoThis();
   }
}


It does not matter what you are pushing into the methods ie their input or output parameters - they are irrelevant.  It's just how you talk to and handle static methods or instance methods which is critical.

If this still does not help please push up your code and indicate the exact line your code is not working from!

**Comment by nishman89** [comment]
```
        public string Dictionary()
        {
            myDictionary.Add("UK", "Birmingham");
            myDictionary.Add("Morocco", "Marakesh");
            myDictionary.Add("France", "Paris");
            myDictionary.Add("India", "New Delhi");
            myDictionary.Add("Norway", "Oslo");
            myDictionary.Add("Thailand", "Bangkok");
            myDictionary.Add("Egypt", "Cairo");
            myDictionary.Add("Australia", "Canberra");
            myDictionary.Add("Japan", "Tokyo");
            myDictionary.Add("Nepal", "Kathmandu");


            foreach (KeyValuePair<string, string> keyValue in myDictionary) // You cannot assign a type KeyValuePair to a string instead you can extract the key and value like this

            {
                var key = keyValue.Key;
                var value = keyValue.Value;
                return string.Format($"Country: {key}\nCapital: {value}\n\n");
            }

            return null;
        }
```


This was the Method (I've updated and added Static to the one I've most recently pushed)

```
        public static void Main()
        {

           Console.WriteLine(Dictionary());

        } 
```


(for example, still working on the best way for the Main method to return the values)

**Comment by philanderson888** [comment]
Yes you've done it right now.

So you can EITHER call

var collectionproject = new CollectionProject();
collectionProject.Dictionary();    // IF NON-STATIC

Or can call

CollectionProject.Dictionary();   // IF STATIC

**Comment by philanderson888** [comment]
I think this is closed now.

In answer to your very specific question in the title

### an object is required for nonstatic fields" mean exactly

The answer is that when we call a non-static member, we require an `instance` to call the member.

var instance = new MyClass();
instance.field...
instance.property...
instance.method...

**Comment by nishman89** [comment]
Issue resolved
