### ISSUE TITLE
ADO.NET Entity Data Model

### ISSUE THREAD

**Issue by nishman89** [nishman89/2019-12_CSharpWalkthrough#8]
Hi Phil,

When I follow these instructions:

Right click on the project in Visual Studio Solution Explorer. Choose Add, New Item, ADO.NET Entity Data Model.

The ADO.NET Entity Data Model item is not there. I've reviewed a YouTube tutorial, however, it appears for them. I've also downloaded the Microsoft.EntitiyFrameworkCore NuGet package, yet this hasn't seemed to do the trick, either. I'm looking at some online guides to resolve the issue, but if you have any idea what the problem is, that would be much appreciated :) Thanks!

**Comment by nishman89** [comment]
Sorted it - instead of adding a .NET Core console app to the solution, then trying to add the ADO.NET Entity Data Model (which didn't appear as an option), I added a .NET Framework Console app to the solution

**Comment by philanderson888** [comment]
Thanks Nish - I did see your comment but was pretty much teaching most of the morning.  That's what I would have said.  

.NET Framework ==> Right click on project and ADD ==> ADO.NET Entity ==> will scaffold full project classes etc for you.
